#ifndef SHOCK_ERROR_H
#define SHOCK_ERROR_H

enum{
  /** 0 SUCCESS **/
  SHOCK_MISSING_USERNAME = 1,
  SHOCK_MISSING_PASSWORD,
  SHOCK_MISSING_SERVER,
  SHOCK_CURL_INIT_ERROR,
  SHOCK_JSON_PRINTER_INIT_ERROR,
  SHOCK_JSON_PARSER_INIT_ERROR,
  SHOCK_CURL_PERFORM_ERROR
}ShockErrorCode;

extern char *ShockErrorString[];

#endif
